// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*)
FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    venue_id,
    name,
    description,
    event_start,
    event_end,
    sale_start,
    sale_end,
    status
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8
)
RETURNING id, venue_id, name, description, event_start, event_end, sale_start, sale_end, status, created_at, updated_at
`

type CreateEventParams struct {
	VenueID     uuid.UUID          `db:"venue_id" json:"venue_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	EventStart  pgtype.Timestamptz `db:"event_start" json:"event_start"`
	EventEnd    pgtype.Timestamptz `db:"event_end" json:"event_end"`
	SaleStart   pgtype.Timestamptz `db:"sale_start" json:"sale_start"`
	SaleEnd     pgtype.Timestamptz `db:"sale_end" json:"sale_end"`
	Status      string             `db:"status" json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.VenueID,
		arg.Name,
		arg.Description,
		arg.EventStart,
		arg.EventEnd,
		arg.SaleStart,
		arg.SaleEnd,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.Description,
		&i.EventStart,
		&i.EventEnd,
		&i.SaleStart,
		&i.SaleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, venue_id, name, description, event_start, event_end, sale_start, sale_end, status, created_at, updated_at
FROM events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.Description,
		&i.EventStart,
		&i.EventEnd,
		&i.SaleStart,
		&i.SaleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, venue_id, name, description, event_start, event_end, sale_start, sale_end, status, created_at, updated_at
FROM events
WHERE
    (
        $1::text IS NULL
        OR status = $1
    )
AND
    (
        $2::timestamptz IS NULL
        OR sale_start >= $2
    )
AND
    (
        $3::timestamptz IS NULL
        OR sale_start <= $3
    )
ORDER BY sale_start
`

type ListEventsParams struct {
	FilterStatus        pgtype.Text        `db:"filter_status" json:"filter_status"`
	FilterStartSaleDate pgtype.Timestamptz `db:"filter_start_sale_date" json:"filter_start_sale_date"`
	FilterEndSaleDate   pgtype.Timestamptz `db:"filter_end_sale_date" json:"filter_end_sale_date"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.FilterStatus, arg.FilterStartSaleDate, arg.FilterEndSaleDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Name,
			&i.Description,
			&i.EventStart,
			&i.EventEnd,
			&i.SaleStart,
			&i.SaleEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    venue_id = $2,
    name = $3,
    description = $4,
    event_start = $5,
    event_end = $6,
    sale_start = $7,
    sale_end = $8,
    status = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, venue_id, name, description, event_start, event_end, sale_start, sale_end, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	VenueID     uuid.UUID          `db:"venue_id" json:"venue_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	EventStart  pgtype.Timestamptz `db:"event_start" json:"event_start"`
	EventEnd    pgtype.Timestamptz `db:"event_end" json:"event_end"`
	SaleStart   pgtype.Timestamptz `db:"sale_start" json:"sale_start"`
	SaleEnd     pgtype.Timestamptz `db:"sale_end" json:"sale_end"`
	Status      string             `db:"status" json:"status"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.VenueID,
		arg.Name,
		arg.Description,
		arg.EventStart,
		arg.EventEnd,
		arg.SaleStart,
		arg.SaleEnd,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.Description,
		&i.EventStart,
		&i.EventEnd,
		&i.SaleStart,
		&i.SaleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
