// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	Status         string             `db:"status" json:"status"`
	TotalAmount    pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BookingSeat struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	BookingID      uuid.UUID          `db:"booking_id" json:"booking_id"`
	SeatID         uuid.UUID          `db:"seat_id" json:"seat_id"`
	PriceAtBooking pgtype.Numeric     `db:"price_at_booking" json:"price_at_booking"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BookingStatusHistory struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	BookingID  uuid.UUID          `db:"booking_id" json:"booking_id"`
	FromStatus pgtype.Text        `db:"from_status" json:"from_status"`
	ToStatus   string             `db:"to_status" json:"to_status"`
	ChangedAt  pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	Note       pgtype.Text        `db:"note" json:"note"`
}

type Event struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	VenueID     uuid.UUID          `db:"venue_id" json:"venue_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	EventStart  pgtype.Timestamptz `db:"event_start" json:"event_start"`
	EventEnd    pgtype.Timestamptz `db:"event_end" json:"event_end"`
	SaleStart   pgtype.Timestamptz `db:"sale_start" json:"sale_start"`
	SaleEnd     pgtype.Timestamptz `db:"sale_end" json:"sale_end"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Payment struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	BookingID      uuid.UUID          `db:"booking_id" json:"booking_id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderRefID  pgtype.Text        `db:"provider_ref_id" json:"provider_ref_id"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	Amount         pgtype.Numeric     `db:"amount" json:"amount"`
	Status         string             `db:"status" json:"status"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type QueueToken struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	EventID     uuid.UUID          `db:"event_id" json:"event_id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Token       string             `db:"token" json:"token"`
	Status      string             `db:"status" json:"status"`
	IssuedAt    pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ActiveUntil pgtype.Timestamptz `db:"active_until" json:"active_until"`
}

type Seat struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	EventID         uuid.UUID          `db:"event_id" json:"event_id"`
	SeatCategoryID  uuid.UUID          `db:"seat_category_id" json:"seat_category_id"`
	SeatCode        string             `db:"seat_code" json:"seat_code"`
	Status          string             `db:"status" json:"status"`
	Version         int32              `db:"version" json:"version"`
	HeldByBookingID pgtype.UUID        `db:"held_by_booking_id" json:"held_by_booking_id"`
	HeldUntil       pgtype.Timestamptz `db:"held_until" json:"held_until"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SeatCategory struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EventID    uuid.UUID          `db:"event_id" json:"event_id"`
	Name       string             `db:"name" json:"name"`
	Price      pgtype.Numeric     `db:"price" json:"price"`
	TotalQuota int32              `db:"total_quota" json:"total_quota"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	FullName     string             `db:"full_name" json:"full_name"`
	PhoneNumber  string             `db:"phone_number" json:"phone_number"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Venue struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Name          string             `db:"name" json:"name"`
	Address       string             `db:"address" json:"address"`
	City          string             `db:"city" json:"city"`
	TotalCapacity int32              `db:"total_capacity" json:"total_capacity"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
