// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countVenues = `-- name: CountVenues :one
SELECT COUNT(*)
FROM venues
`

func (q *Queries) CountVenues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVenues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    name,
    address,
    city,
    total_capacity
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, address, city, total_capacity, created_at
`

type CreateVenueParams struct {
	Name          string `db:"name" json:"name"`
	Address       string `db:"address" json:"address"`
	City          string `db:"city" json:"city"`
	TotalCapacity int32  `db:"total_capacity" json:"total_capacity"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.TotalCapacity,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.TotalCapacity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues
WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVenue, id)
	return err
}

const getVenueById = `-- name: GetVenueById :one
SELECT id, name, address, city, total_capacity, created_at
FROM venues
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVenueById(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueById, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.TotalCapacity,
		&i.CreatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, address, city, total_capacity, created_at
FROM venues
ORDER BY created_at DESC
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.TotalCapacity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET
    name = $2,
    address = $3,
    city = $4,
    total_capacity = $5
WHERE id = $1
RETURNING id, name, address, city, total_capacity, created_at
`

type UpdateVenueParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Address       string    `db:"address" json:"address"`
	City          string    `db:"city" json:"city"`
	TotalCapacity int32     `db:"total_capacity" json:"total_capacity"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.TotalCapacity,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.TotalCapacity,
		&i.CreatedAt,
	)
	return i, err
}
