// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ==========================================
	// Utility
	// ==========================================
	CountUsers(ctx context.Context) (int64, error)
	// ==========================================
	// Create
	// ==========================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ==========================================
	// Delete
	// ==========================================
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ExistsUserByEmail(ctx context.Context, email string) (bool, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ==========================================
	// Read
	// ==========================================
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	// ==========================================
	// Update
	// ==========================================
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
